# 服务端口
server:
  port: 10086
# 服务名称
spring:
  application:
    name: ly-register
# 注册配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    fetch-registry: false  # 不拉取服务
    register-with-eureka: false   # 不注册自己