server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis-plus:
  #mybatis-plus配置别名和加载mapper配置文件
  type-aliases-package: com.bj1901.item.domain
  mapper-locations: classpath*:/mapper/*.xml
  #mybatis-plus配置控制台打印完整带参数SQL语句
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl